// <auto-generated>
//     Generated by Tools -> Axie Mixer 3D -> Update Weapon Anim Catalog (AxieWeaponAnimUpdater).
//     Do NOT edit by hand; re-run the weapon data-update tool to regenerate.
// </auto-generated>

namespace SkyMavis.AxieMixer3D.WeaponAnims
{
    /// <summary>
    /// Typed weapon/action animation clip names (bare — no "Action." prefix). These are the names
    /// that leave the main package's <c>AnimNames</c> when the weapon clips are split out.
    /// Note: the Cannon weapon is baked as "Canon" in the source art; the tool normalizes it, so the
    /// constants read "Cannon*" (double n).
    /// </summary>
    public static class WeaponAnimNames
    {
        public const string AttackCombo = "AttackCombo";
        public const string AttackHead = "AttackHead";
        public const string AttackRange = "AttackRange";
        public const string AxeAttack = "AxeAttack";
        public const string AxeIdle = "AxeIdle";
        public const string AxeRun = "AxeRun";
        public const string AxeSkill = "AxeSkill";
        public const string AxeWalk = "AxeWalk";
        public const string BowAttack = "BowAttack";
        public const string BowIdle = "BowIdle";
        public const string BowRun = "BowRun";
        public const string BowSkill = "BowSkill";
        public const string BowWalk = "BowWalk";
        public const string BrushAttack = "BrushAttack";
        public const string BrushIdle = "BrushIdle";
        public const string BrushRun = "BrushRun";
        public const string BrushWalk = "BrushWalk";
        public const string CannonAttack = "CannonAttack";
        public const string CannonIdle = "CannonIdle";
        public const string CannonRun = "CannonRun";
        public const string CannonSkill = "CannonSkill";
        public const string CannonWalk = "CannonWalk";
        public const string CutTree = "CutTree";
        public const string DaggerAttack = "DaggerAttack";
        public const string DaggerIdle = "DaggerIdle";
        public const string DaggerRun = "DaggerRun";
        public const string DaggerSkill = "DaggerSkill";
        public const string DaggerWalk = "DaggerWalk";
        public const string FlagAttack = "FlagAttack";
        public const string FlagIdle = "FlagIdle";
        public const string FlagRun = "FlagRun";
        public const string FlagSkill = "FlagSkill";
        public const string FlagWalk = "FlagWalk";
        public const string FluteAttack = "FluteAttack";
        public const string FluteIdle = "FluteIdle";
        public const string FluteRun = "FluteRun";
        public const string FluteSkill = "FluteSkill";
        public const string FluteWalk = "FluteWalk";
        public const string GauntletAttack = "GauntletAttack";
        public const string GauntletIdle = "GauntletIdle";
        public const string GauntletRun = "GauntletRun";
        public const string GauntletSkill = "GauntletSkill";
        public const string GauntletWalk = "GauntletWalk";
        public const string HammerAttack = "HammerAttack";
        public const string HammerIdle = "HammerIdle";
        public const string HammerRun = "HammerRun";
        public const string HammerSkill = "HammerSkill";
        public const string HammerWalk = "HammerWalk";
        public const string HitTree = "HitTree";
        public const string IdleCarryItem = "IdleCarryItem";
        public const string IdleGetHit = "IdleGetHit";
        public const string LanternAttack = "LanternAttack";
        public const string LanternIdle = "LanternIdle";
        public const string LanternRun = "LanternRun";
        public const string LanternSkill = "LanternSkill";
        public const string LanternWalk = "LanternWalk";
        public const string LootItem = "LootItem";
        public const string MalaAttack = "MalaAttack";
        public const string MalaIdle = "MalaIdle";
        public const string MalaRun = "MalaRun";
        public const string MalaSkill = "MalaSkill";
        public const string MalaWalk = "MalaWalk";
        public const string PourWater = "PourWater";
        public const string Shoveling = "Shoveling";
        public const string SpearAttack = "SpearAttack";
        public const string SpearIdle = "SpearIdle";
        public const string SpearRun = "SpearRun";
        public const string SpearSkill = "SpearSkill";
        public const string SpearWalk = "SpearWalk";
        public const string StaffAttack = "StaffAttack";
        public const string StaffIdle = "StaffIdle";
        public const string StaffRun = "StaffRun";
        public const string StaffSkill = "StaffSkill";
        public const string StaffWalk = "StaffWalk";
        public const string StoneHarvest = "StoneHarvest";
        public const string SwordAttack = "SwordAttack";
        public const string SwordAttackv2 = "SwordAttackv2";
        public const string SwordIdle = "SwordIdle";
        public const string SwordRun = "SwordRun";
        public const string SwordSkill = "SwordSkill";
        public const string SwordSkill2 = "SwordSkill2";
        public const string SwordWalk = "SwordWalk";
        public const string TalismanAttack = "TalismanAttack";
        public const string TalismanIdle = "TalismanIdle";
        public const string TalismanRun = "TalismanRun";
        public const string TalismanSkill = "TalismanSkill";
        public const string TalismanWalk = "TalismanWalk";
        public const string TomeAttack = "TomeAttack";
        public const string TomeIdle = "TomeIdle";
        public const string TomeRun = "TomeRun";
        public const string TomeSkill = "TomeSkill";
        public const string TomeWalk = "TomeWalk";
        public const string WhipAttack = "WhipAttack";
        public const string WhipIdle = "WhipIdle";
        public const string WhipRun = "WhipRun";
        public const string WhipSkill = "WhipSkill";
        public const string WhipWalk = "WhipWalk";
    }
}
