// <auto-generated>
//     Generated by Tools -> Axie Mixer 3D -> Update Axie Data (AxieDataUpdater).
//     Do NOT edit by hand; re-run the data-update tool to regenerate.
// </auto-generated>

namespace SkyMavis.AxieMixer3D
{
    /// <summary>
    /// Typed body-animation clip names (bare — no "Default."/"Action." prefix).
    /// Note: the Cannon weapon is baked as "Canon" in the source art; the data-update
    /// tool normalizes it, so the constants read "Cannon*" (double n).
    /// </summary>
    public static class AnimNames
    {
        public const string Dead = "Dead";
        public const string Idle = "Idle";
        public const string IdleCarryItem = "IdleCarryItem";
        public const string IdleGetHit = "IdleGetHit";
        public const string Run = "Run";
        public const string RunAttack = "RunAttack";
        public const string RunCarryItem = "RunCarryItem";
        public const string Stun = "Stun";
        public const string Walk = "Walk";
        public const string WalkAttack = "WalkAttack";
        public const string WalkCarryItem = "WalkCarryItem";
    }
}
